module.exports = {
    language: {
        name: 'zh'
    },
    SignIn: {
        SignIn: '登录'
    },
    Select: {
        Select: '请选择'
    },
    UserName: {
        UserNameMessage: '请输入您的用户名'
    },
    passWord: {
        passwordMessage: "请输入您的密码"
    },
    home: {
        home: '监控主页'
    },
    FireMonitor: {
        FireMonitor: '火灾监控'
    },
    ElectricalMonitor: {
        ElectricalMonitor: '电气火灾监控'
    },
    FacilitiesMonitor: {
        FacilitiesMonitor: '消防设施监控页'
    },
    AlarmController: {
        AlarmController: '报警控制器监控页'
    },
    DtuGateway: {
        DtuGateway: '通讯装置'
    },
    deviceStatus: {
        unknown: "未知",
        Normal: "正常",
        Alarming: "报警",
        batteryLow: "低电量",
        doorClosed: "门关闭"
    },
    Index: {
        principal: "负责人",
        Contact: "联系人",
        AddressInfo: "地址信息",
        electricalFire: "电器火灾",
        fireMonitoring: "火灾监控",
        fireFacilities: "消防设施",
        alarmController: "报警控制器",
        communicationDevice: "通讯装置",
        statistics: '数据统计图例',
        eventList: '事件列表',
        stateTrend: '状态趋势图',
        stateStatistics: '状态统计图',
        statisticsChart: '数量统计图',
        eventName: '事件名称',
        time: '时间',
        equipmentName: '设备名称',
        address: '地址',
        all: '全部',
        Information: '设备信息',
        DeviceID: '设备编码',
        Type: '设备类型',
        Status: '设备状态',
        Details: '设备详情',
        submit: '提交',
        cancel: '取消',
        Basic: '基本信息',
        Quantity: '数量/次',
        A: '台/个',
        placeholder: '请输入内容',
        event: {
            eventDetails: "事件详情",
            EventInformation: '事件信息',
            name: '事件名称',
            grade: '事件等级',
            Time: '发生时间',
        },
        Device: {
            DeviceInfo: '设备详情',
            Types: '类型',
            Numbering: '编号',
            status: '状态',
            QRCode: '查看二维码',
            batteryPower: '电池电量',
            checkInTime: '登记时间',
            moduleMethod: '通讯方式',
            module: '通讯模块编码',
            Manufacturer: '生产厂家'
        },
        Installation: {
            Information: '安装信息',
            unit: '单位',
            area: '区域',
            Address: '详细地址',
            Contact: '联系人',
            phone: '联系方式',
            place: '场所',
            time: '安装时间',
            Partition: '分区',
            number: '安装编号'
        },
        otherInformation: {
            otherInformation: "其他信息",
            currentValue: "当前值",
            alarmUpperLimit: '报警上限值',
            alarmLowerLimit: '报警下限值',
            upperWarningLimit: '预警上限值',
            lowerWarningLimit: '预警下限值',
            currentState: '当前状态',
            defaultState: '默认状态'
        },
        Qualitative: '事件定性',
        eventDealWith: '事件处理',
        closeEvenDesc: '是否关闭当前事件',
        true: '是',
        false: '否',
        dealWith: '处理',
        More: '更多',
        channelDetails: '通道详情',
        service: '维修'
    },
    FireMonitoring: {
        InstallationNumber: '安装编号',
        EquipmentName: '全部',
        EquipmentNumber: '设备编码',
        status: '全部',
        State: '状态',
        Area: '区域',
        Address: '地址',
        Details: '详情',
        Hint: "请输入设备编码"
    },
    ElectricalMonitoring: {
        addrNum: '地址码',
        coding: "设备编码",
        name: "设备名称",
        status: '设备状态',
        area: '设备区域',
        address: '地址',
        Reset: '复位',
        Loop: '回路',
        value: "当前值",
        LoopStatus: "状态",
        operating: "操作",
        history: '历史记录',
        Record: {
            startTime: "开始日期",
            endTime: "结束日期",
            lastWeek: "最近一周",
            lastMonth: "最近一个月",
            lastThreeMonths: "最近三个月"
        },
        gangway:{
            Details:"通道信息",
            addressCode:"地址码",
            gangwayTypes:"通道类型",
            gangwayNumber:"通道号",
            status:"状态",
            value:"监测值",
            upperLimit:"上限值",
            lowerLimit:"下限值"
        }
    },
    Water: {
        name: "名称",
        coding: "编码",
        area: '区域',
        address: '地址',
        Types: '设备类型',
        status: '当前状态',
        hint: "请输入设备编码"
    },
    Controller: {
        AbnormalNode: '异常节点',
        Machine: '机号',
        Circuit: '回路号',
        Node: '节点号',
        Type: '节点类型',
        status: '节点状态',
        Partition: '分区',
        address: '地址',
        time: '时间',
        operating: '操作',
        area: '区域',
        history: '历史纪录',
        Contrstatus: '控制器状态',
        ControllerNumber: '控制器号',
        Details: '详情',
        ControllerList: '控制器列表',
        Loop: {
            loopDetails:'回路详情',
            circuit: "回路号",
            types: '回路类型',
            Point: "节点号",
            nodeType: '节点类型',
            status: '状态',
            Partition: '分区',
            time: '时间'
        }
    },
    Newsletter: {
        deviceID: '设备编号',
        status: '状态',
        area: '区域',
        address: '地址',
        Details: '详情',
        All: '全部'
    }
}