module.exports = {
    language: {
        name: 'zh'
    },
    SignIn: {
        SignIn: '登录'
    },
    Select: {
        Select: '请选择'
    },
    UserName: {
        UserNameMessage: '请输入您的用户名'
    },
    passWord: {
        passwordMessage: "请输入您的密码"
    },
    home: {
        home: '监控主页'
    },
    FireMonitor: {
        FireMonitor: '火灾监控'
    },
    ElectricalMonitor: {
        ElectricalMonitor: '电气火灾监控'
    },
    FacilitiesMonitor: {
        FacilitiesMonitor: '消防设施监控页'
    },
    AlarmController: {
        AlarmController: '报警控制器监控页'
    },
    DtuGateway: {
        DtuGateway: '通选装置'
    },
    deviceStatus: {
        unknown: "未知",
        Normal: "正常",
        Alarming: "报警",
        batteryLow: "低电量",
        doorClosed: "门关闭"
    },
    Index: {
        principal: "负责人",
        Contact: "联系人",
        AddressInfo: "地址信息",
        electricalFire: "电器火灾",
        fireMonitoring: "火灾监控",
        fireFacilities: "消防设施",
        alarmController: "报警控制器",
        communicationDevice: "通讯装置"
    }
}