module.exports = {
    language: {
        name: 'zh'
    },
    SignIn: {
        SignIn: '登录'
    },
    Select: {
        Select: '请选择'
    },
    UserName: {
        UserNameMessage: '请输入您的用户名'
    },
    passWord: {
        passwordMessage: "请输入您的密码"
    },
    home: {
        home: '监控主页'
    },
    FireMonitor: {
        FireMonitor: '火灾监控'
    },
    ElectricalMonitor: {
        ElectricalMonitor: '电气火灾监控'
    },
    FacilitiesMonitor: {
        FacilitiesMonitor: '消防设施监控页'
    },
    AlarmController: {
        AlarmController: '报警控制器监控页'
    },
    DtuGateway: {
        DtuGateway: '通讯装置'
    },
    deviceStatus: {
        unknown: "未知",
        Normal: "正常",
        Alarming: "报警",
        batteryLow: "低电量",
        doorClosed: "门关闭"
    },
    Index: {
        principal: "负责人",
        Contact: "联系人",
        AddressInfo: "地址信息",
        electricalFire: "电器火灾",
        fireMonitoring: "火灾监控",
        fireFacilities: "消防设施",
        alarmController: "报警控制器",
        communicationDevice: "通讯装置",
        statistics: '数据统计图例',
        eventList: '事件列表',
        stateTrend: '状态趋势图',
        stateStatistics: '状态统计图',
        statisticsChart: '数量统计图',
        eventName: '事件名称',
        time: '时间',
        equipmentName: '设备名称',
        address: '地址'
    },
    FireMonitoring: {
        InstallationNumber: '安装编号',
        EquipmentName: '设备名称',
        EquipmentNumber: '设备编码',
        State: '当前状态',
        Area: '区域',
        Address: '地址',
        Details: '详情'
    },
    ElectricalMonitoring: {
        coding: "设备编码",
        name: "设备名称",
        status: '设备状态',
        area: '设备区域',
        address: '地址',
        Reset: '复位',
        Loop: '回路',
        value: "当前值",
        LoopStatus: "状态",
        operating: "操作",
        history: '历史记录'
    }
}