module.exports = {
    language: {
        name: 'en'
    },
    SignIn: {
        SignIn: 'Sign in'
    },
    Select: {
        Select: ' Select'
    },
    UserName: {
        UserNameMessage: ' Enter Your Login Name'
    },
    passWord: {
        passwordMessage: " Enter Your Password"
    },
    home: {
        home: 'Home'
    },
    FireMonitor: {
        FireMonitor: 'Fire Monitor'
    },
    ElectricalMonitor: {
        ElectricalMonitor: 'Electrical Monitor'
    },
    FacilitiesMonitor: {
        FacilitiesMonitor: 'Facilities Monitor'
    },
    AlarmController: {
        AlarmController: 'Alarm Controller'
    },
    DtuGateway: {
        DtuGateway: 'DTU/Gateway'
    },
    deviceStatus: {
        unknown: "unknown",
        Normal: "Normal",
        Alarming: "Alarming",
        batteryLow: "batteryLow",
        doorClosed: "doorClosed"
    },
    Index: {
        principal: "principal",
        Contact: "Contact",
        AddressInfo: "AddressInfo",
        electricalFire: "Electrical",
        fireMonitoring: "Monitoring",
        fireFacilities: "Facilities",
        alarmController: "Controller",
        communicationDevice: "Communication",
        statistics: 'Statistics',
        eventList: 'EventList'
    }
}