module.exports = {
    language: {
        name: 'en'
    },
    SignIn: {
        SignIn: 'Sign in'
    },
    Select: {
        Select: ' Select'
    },
    UserName: {
        UserNameMessage: ' Enter Your Login Name'
    },
    passWord: {
        passwordMessage: " Enter Your Password"
    },
    home: {
        home: 'Home'
    },
    FireMonitor: {
        FireMonitor: 'Fire Monitor'
    },
    ElectricalMonitor: {
        ElectricalMonitor: 'Electrical Monitor'
    },
    FacilitiesMonitor: {
        FacilitiesMonitor: 'Facilities Monitor'
    },
    AlarmController: {
        AlarmController: 'Alarm Controller'
    },
    DtuGateway: {
        DtuGateway: 'DTU/Gateway'
    },
    deviceStatus: {
        unknown: "unknown",
        Normal: "Normal",
        Alarming: "Alarming",
        batteryLow: "batteryLow",
        doorClosed: "doorClosed"
    },
    Index: {
        principal: "principal",
        Contact: "Contact",
        AddressInfo: "AddressInfo",
        electricalFire: "Electrical",
        fireMonitoring: "Monitoring",
        fireFacilities: "Facilities",
        alarmController: "Controller",
        communicationDevice: "Communication",
        statistics: 'Statistics',
        eventList: 'EventList',
        stateTrend: 'StateTrend',
        stateStatistics: 'StateStatistics',
        statisticsChart: 'StatisticsChart',
        eventName: 'EventName',
        time: 'Time',
        equipmentName: 'EquipmentName',
        address: 'Address',
        all: 'All',
        Information: 'Information',
        DeviceID: 'DeviceID',
        Type: 'Type',
        Status: 'Status',
        Details: 'Details',
        event: {
            eventDetails: "EventDetails",
            EventInformation: 'EventInformation',
            name: 'Name',
            grade: 'Grade',
            Time: 'Time',
        },
        Device: {
            DeviceInfo: 'DeviceInfo',
            Types: 'Types',
            Numbering: 'Numbering',
            status: 'Status',
            QRCode: 'QRCode',
            batteryPower: 'BatteryPower',
            checkInTime: 'CheckInTime',
            module: 'Module'
        },
        Installation: {
            Information: 'InstallationInfo',
            unit: 'Unit',
            area: 'Area',
            Address: 'Address',
            Contact: 'Contact',
            phone: 'Phone',
            place: 'Place',
            time: 'Time',
            Partition: 'Partition',
            number: 'Number'
        },
        dealWith: 'DealWith',
        More: 'More'
    },
    FireMonitoring: {
        InstallationNumber: 'Installation',
        EquipmentName: 'Name',
        EquipmentNumber: 'EquipmentNumber',
        State: 'State',
        Area: 'Area',
        Address: 'Address',
        Details: 'Details',
        Hint: "Please enter the device number"
    },
    ElectricalMonitoring: {
        coding: "Coding",
        name: "Name",
        status: 'Status',
        area: 'Area',
        address: 'Address',
        Reset: 'Reset',
        Loop: 'Loop',
        value: "Value",
        LoopStatus: "LoopStatus",
        operating: "Operating",
        history: 'History'
    },
    Water: {
        name: "Name",
        coding: "Coding",
        area: 'Area',
        address: 'Address',
        Types: 'Types',
        status: 'Status',
        hint: "Please enter the device number"
    },
    Controller: {
        AbnormalNode: 'AbnormalNode',
        Machine: 'Machine',
        Circuit: 'Circuit',
        Node: 'Node',
        Type: 'Type',
        status: 'Status',
        Partition: 'Partition',
        address: 'Address',
        time: 'Time',
        operating: 'operating',
        area: 'Area',
        history: 'History',
        Contrstatus: 'Contrstatus',
        ControllerNumber: 'ControllerNumber',
        ControllerList: 'ControllerList',
    },
    Newsletter: {
        deviceID: 'DeviceID',
        status: 'Status',
        area: 'Area',
        address: 'Address',
        Details: 'Details',
        All: 'ALL'
    }
}